// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qervsmuslngghgpptbdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlcnZzbXVzbG5nZ2hncHB0YmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjA4MjUsImV4cCI6MjA2OTUzNjgyNX0.gwtMVHeQUF91nZYUsXrHH9xH7RN-QMUAnujhcdm8FUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});